# Use the official MediaMTX image which includes FFmpeg on arm64
FROM bluenviron/mediamtx:latest-ffmpeg
# Set working directory
WORKDIR /
# Copy the config file into the container
COPY mediamtx.yml /mediamtx.yml
